[package]
name = "pocorgtfo-mirror"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
itertools = "0.7.8"
serde = "1.0.68"
serde_derive = "1.0.68"
serde_json = "1.0.22"
sha-1 = "0.7.0"
sha2 = "0.7.1"