[package]
name = "pocorgtfo-mirror"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2021"

[dependencies]
itertools = "0.7.11"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
sha-1 = "0.7.0"
sha2 = "0.7.1"
